//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yttrium.DbManifest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yttrium.DbManifest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if exists ( select id from sys.objects where name = &apos;{0}&apos; and xtype in ( &apos;FN&apos;, &apos;IF&apos;, &apos;TF&apos;, &apos;FS&apos;, &apos;FT&apos; ) )
        ///    drop function {0};
        ///go
        ///
        ///{1}
        ///go
        ///
        ////* eof */.
        /// </summary>
        internal static string SkelFunction {
            get {
                return ResourceManager.GetString("SkelFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if exists ( select id from sys.procedures where name = &apos;{0}&apos; )
        ///    drop procedure {0};
        ///go
        ///
        ///{1}
        ///go
        ///
        ////* eof */.
        /// </summary>
        internal static string SkelProcedure {
            get {
                return ResourceManager.GetString("SkelProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if exists ( select id from sys.views where name = &apos;{0}&apos; )
        ///    drop view {0};
        ///go
        ///
        ///{1}
        ///go
        ///
        ////* eof */.
        /// </summary>
        internal static string SkelView {
            get {
                return ResourceManager.GetString("SkelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- $Id: Resources.Designer.cs 34 2014-10-23 16:40:59Z lft $ --&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:m=&quot;urn:yttrium:dbmanifest&quot;
        ///    xmlns:eo=&quot;urn:eo&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///
        ///    &lt;xsl:output method=&quot;text&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///
        ///    &lt;xsl:template match=&quot; m:manifest &quot;&gt;
        ///        &lt;xsl:text&gt;DB &lt;/xsl:text&gt;
        ///        &lt;xsl:value-of select=&quot; eo:pad( m:database/@name, 25 ) &quot; /&gt;
        ///        &lt;xsl:text xml:space=&quot;preserve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ToConsole {
            get {
                return ResourceManager.GetString("ToConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- $Id: Resources.Designer.cs 34 2014-10-23 16:40:59Z lft $ --&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///
        ///    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; /&gt;
        ///
        ///    &lt;xsl:param name=&quot;IncludeComments&quot; select=&quot; &apos;false&apos; &quot; /&gt;
        ///
        ///
        ///    &lt;!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ///    ~
        ///    ~ Manifest root
        ///    ~
        ///    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ToManifest {
            get {
                return ResourceManager.GetString("ToManifest", resourceCulture);
            }
        }
    }
}
