<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:msxsl="urn:schemas-microsoft-com:xslt"
    xmlns:p="urn:platinum/actor/exception"
    xmlns:fn="urn:eo-util"
    exclude-result-prefixes="msxsl p fn">

    <xsl:output method="text" indent="no" />

    <xsl:param name="ToolVersion" />
    <xsl:param name="FileName" />
    <xsl:param name="FullFileName" />
    <xsl:param name="Namespace" />


    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ~
    ~ p:exceptions/
    ~
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <xsl:template match=" p:exceptions ">
        <xsl:text>// autogenerated: do NOT edit manually
using Platinum;
using System;

namespace </xsl:text>

        <xsl:value-of select=" $Namespace " />
        <xsl:text>
{</xsl:text>
        <xsl:apply-templates select=" p:add " />
        <xsl:text>
}

/* eof */</xsl:text>
    </xsl:template>


    <xsl:template match=" p:add ">
        <xsl:if test=" position() > 1 ">
            <xsl:text>
</xsl:text>
        </xsl:if>

        <xsl:text>
    [Serializable]
    [Resx( "</xsl:text>
        <xsl:value-of select=" $Namespace " />
        <xsl:text>.ER" )]
    public class </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text> : ResxActorException
    {
        public </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text>( string code )
            : base( code )
        {
        }

        public </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text>( string code, Exception innerException )
            : base( code, innerException )
        {
        }

        public </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text>( string code, params object[] args )
            : base( code, args )
        {
        }

        public </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text>( string code, Exception innerException, params object[] args )
            : base( code, innerException, args )
        {
        }
    }</xsl:text>
    </xsl:template>


</xsl:stylesheet>
