<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:msxsl="urn:schemas-microsoft-com:xslt"
    xmlns:p="urn:platinum/actor/exception"
    xmlns:fn="urn:eo-util"
    exclude-result-prefixes="msxsl p fn">

    <xsl:output method="text" indent="no" />

    <xsl:param name="ToolVersion" />
    <xsl:param name="FileName" />
    <xsl:param name="FullFileName" />
    <xsl:param name="Namespace" />

    <xsl:variable name="NewLine">
        <xsl:text>
</xsl:text>
    </xsl:variable>


    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ~
    ~ p:exceptions/
    ~
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <xsl:template match=" p:exceptions ">
        <xsl:text>// autogenerated: do NOT edit manually
using Platinum;
using System;

namespace </xsl:text>

        <xsl:value-of select=" $Namespace " />
        <xsl:text>
{</xsl:text>
        <xsl:apply-templates select=" p:add " />
        <xsl:text>
}

/* eof */</xsl:text>
    </xsl:template>


    <xsl:template match=" p:add ">
        <xsl:if test=" position() > 1 ">
            <xsl:value-of select=" $NewLine " />
            <xsl:value-of select=" $NewLine " />
        </xsl:if>

        <xsl:value-of select=" $NewLine " />
        <xsl:call-template name="p:summary">
            <xsl:with-param name="indent" select=" '    ' " />
        </xsl:call-template>
        <xsl:call-template name="p:remarks">
            <xsl:with-param name="indent" select=" '    ' " />
        </xsl:call-template>
        <xsl:text>    [Serializable]
    [Resx( "</xsl:text>
        <xsl:value-of select=" $Namespace " />
        <xsl:text>.ER" )]
    public class </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text> : ResxActorException
    {
        /// &lt;summary /&gt;
        public </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text>( string code )
            : base( code )
        {
        }


        /// &lt;summary /&gt;
        public </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text>( string code, Exception innerException )
            : base( code, innerException )
        {
        }


        /// &lt;summary /&gt;
        public </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text>( string code, params object[] args )
            : base( code, args )
        {
        }


        /// &lt;summary /&gt;
        public </xsl:text>
        <xsl:value-of select=" @name " />
        <xsl:text>( string code, Exception innerException, params object[] args )
            : base( code, innerException, args )
        {
        }
    }</xsl:text>
    </xsl:template>


    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ~
    ~ y:summary/
    ~ y:remarks/
    ~
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <xsl:template name="p:summary">
        <xsl:param name="indent" select=" '        ' " />

        <xsl:choose>
            <xsl:when test=" p:summary ">
                <xsl:value-of select=" $indent " />
                <xsl:text>/// &lt;summary&gt;</xsl:text>
                <!-- This new line not needed! -->

                <xsl:value-of select=" fn:ToWrap( p:summary/text(), concat( $indent, '/// ' ), 80 ) "/>
                <xsl:value-of select=" $NewLine " />

                <xsl:value-of select=" $indent " />
                <xsl:text>/// &lt;/summary&gt;</xsl:text>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select=" $indent " />
                <xsl:text>/// &lt;summary /&gt;</xsl:text>
            </xsl:otherwise>
        </xsl:choose>
        <xsl:value-of select=" $NewLine " />
    </xsl:template>

    <xsl:template name="p:remarks">
        <xsl:param name="indent" select=" '        ' " />

        <xsl:if test=" p:remarks ">
            <xsl:value-of select=" $indent " />
            <xsl:text>/// &lt;remarks&gt;</xsl:text>
            <!-- This new line not needed! -->

            <xsl:value-of select=" fn:ToWrap( p:remarks/text(), concat( $indent, '/// ' ), 80 ) "/>
            <xsl:value-of select=" $NewLine " />

            <xsl:value-of select=" $indent " />
            <xsl:text>/// &lt;/remarks&gt;</xsl:text>
            <xsl:value-of select=" $NewLine " />
        </xsl:if>
    </xsl:template>


</xsl:stylesheet>
