// autogenerated: do NOT edit manually
using CustomToolGenerator;
using System;
using System.Configuration;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace Yttrium.VisualStudio
{
    [ComVisible( true )]
    [Guid( "d607f2cd-936b-4766-81cb-54adcbecbd43" )]
    public partial class ConfigGenTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ConfigGenTool );
            string desc = "Configuration class generation tool";

            Registration.RegisterCustomTool( "YConfigGenTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ConfigGenTool );

            Registration.UnregisterCustomTool( "YConfigGenTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "25ad5f8e-42cc-4e00-8edb-99acbb2dfc28" )]
    public partial class FileGetTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( FileGetTool );
            string desc = "Simplifies downloading files.";

            Registration.RegisterCustomTool( "YFileGetTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( FileGetTool );

            Registration.UnregisterCustomTool( "YFileGetTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "03fbc084-5c54-4a98-96ca-34133dd8f383" )]
    public partial class ResxErrorTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ResxErrorTool );
            string desc = "Supports ResxActorException asset generation";

            Registration.RegisterCustomTool( "YResxErrorTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ResxErrorTool );

            Registration.UnregisterCustomTool( "YResxErrorTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "832b2379-8ac9-4ad5-8f71-8910cb6d3149" )]
    public partial class ResxExceptionTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ResxExceptionTool );
            string desc = "Generates ResxException derived classes";

            Registration.RegisterCustomTool( "YResxExceptionTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ResxExceptionTool );

            Registration.UnregisterCustomTool( "YResxExceptionTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "80392f8e-3396-4043-abd1-9da68f63ac8d" )]
    public partial class WsdlTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( WsdlTool );
            string desc = "Generates a proxy file";

            Registration.RegisterCustomTool( "YWsdlTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( WsdlTool );

            Registration.UnregisterCustomTool( "YWsdlTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "e0dff0ac-0924-48e2-8f14-65f7077996c2" )]
    public partial class XsdTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( XsdTool );
            string desc = "Runs xsd.exe command-line tool over schema.";

            Registration.RegisterCustomTool( "YXsdTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( XsdTool );

            Registration.UnregisterCustomTool( "YXsdTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "288117e1-c244-4d0d-81fd-9d5f29e28041" )]
    public partial class XsltTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( XsltTool );
            string desc = "XSLT transformer";

            Registration.RegisterCustomTool( "YXsltTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( XsltTool );

            Registration.UnregisterCustomTool( "YXsltTool", category, type );
        }
    }
}

/* eof */
