// autogenerated: do NOT edit manually
using CustomToolGenerator;
using System;
using System.Configuration;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace Yttrium.VisualStudio
{
    [ComVisible( true )]
    [Guid( "bc18e15c-b63b-4dfc-b993-a94d1dd11664" )]
    public partial class ConfigGenTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ConfigGenTool );
            string desc = "Configuration class generation tool";

            Registration.RegisterCustomTool( "ConfigGenTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ConfigGenTool );

            Registration.UnregisterCustomTool( "ConfigGenTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "af375fa8-e16a-49db-a0aa-672b7b8c3f36" )]
    public partial class FileGetTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( FileGetTool );
            string desc = "Simplifies downloading files.";

            Registration.RegisterCustomTool( "FileGetTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( FileGetTool );

            Registration.UnregisterCustomTool( "FileGetTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "69466aa6-8409-4d15-9b7e-69b3a19c2686" )]
    public partial class ResxErrorTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ResxErrorTool );
            string desc = "Supports ResxActorException asset generation";

            Registration.RegisterCustomTool( "ResxErrorTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ResxErrorTool );

            Registration.UnregisterCustomTool( "ResxErrorTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "283bcca6-42f7-486a-9ac6-956385dc9338" )]
    public partial class ResxExceptionTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ResxExceptionTool );
            string desc = "Generates ResxException derived classes";

            Registration.RegisterCustomTool( "ResxExceptionTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( ResxExceptionTool );

            Registration.UnregisterCustomTool( "ResxExceptionTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "384814a8-0c01-49f5-b934-c304bd0d854c" )]
    public partial class WsdlTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( WsdlTool );
            string desc = "Generates a proxy file";

            Registration.RegisterCustomTool( "WsdlTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( WsdlTool );

            Registration.UnregisterCustomTool( "WsdlTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "3ad049bc-27e0-4e4c-b225-247c62f554b5" )]
    public partial class XsdTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( XsdTool );
            string desc = "Runs xsd.exe command-line tool over schema.";

            Registration.RegisterCustomTool( "XsdTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( XsdTool );

            Registration.UnregisterCustomTool( "XsdTool", category, type );
        }
    }

    [ComVisible( true )]
    [Guid( "027cef63-68b2-43e0-ba77-fe14d1bfe870" )]
    public partial class XsltTool : BaseTool
    {
        [ComRegisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void RegisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( XsltTool );
            string desc = "XSLT transformer";

            Registration.RegisterCustomTool( "XsltTool", category, type, desc );
        }

        [ComUnregisterFunction]
        [SuppressMessage( "Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "t" )]
        private static void UnregisterClass( Type t )
        {
            Guid category = Registration.CSharpCategoryGuid;
            Type type = typeof( XsltTool );

            Registration.UnregisterCustomTool( "XsltTool", category, type );
        }
    }
}

/* eof */
